### ISSUE TITLE
Can define tables multiple times

### ISSUE THREAD

**Issue by mattyhall** [mattyhall/tomlz#1]
We currently except

```toml
[foo]
bar = 1

[foo]
baz = 2
```

which the spec says should not be allowed

Note that the following is legal:

```toml
[x.y.z.w]

[x] # defining a super-table afterward is ok
```
